### ISSUE TITLE
"gem install yajl-ruby" fails on osx 10.9

### ISSUE THREAD

**Issue by sneak** [brianmario/yajl-ruby#124]
<pre>
Installing gem yajl-ruby-1.1.0
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/.gitignore
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/.rspec
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/.travis.yml
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/CHANGELOG.md
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/Gemfile
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/MIT-LICENSE
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/README.md
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/Rakefile
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/encode.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/encode_json_and_marshal.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/encode_json_and_yaml.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/http.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/parse.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/parse_json_and_marshal.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/parse_json_and_yaml.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/parse_stream.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/subjects/item.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/subjects/ohai.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/subjects/ohai.marshal_dump
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/subjects/ohai.yml
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/subjects/twitter_search.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/subjects/twitter_stream.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/benchmark/subjects/unicode.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/examples/encoding/chunked_encoding.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/examples/encoding/one_shot.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/examples/encoding/to_an_io.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/examples/http/twitter_search_api.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/examples/http/twitter_stream_api.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/examples/parsing/from_file.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/examples/parsing/from_stdin.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/examples/parsing/from_string.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/api/yajl_common.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/api/yajl_gen.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/api/yajl_parse.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/api/yajl_version.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/extconf.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl.c
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_alloc.c
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_alloc.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_buf.c
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_buf.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_bytestack.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_encode.c
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_encode.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_ext.c
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_ext.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_gen.c
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_lex.c
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_lex.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_parser.c
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_parser.h
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/yajl_version.c
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/bzip2.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/bzip2/stream_reader.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/bzip2/stream_writer.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/deflate.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/deflate/stream_reader.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/deflate/stream_writer.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/gzip.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/gzip/stream_reader.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/gzip/stream_writer.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/http_stream.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/json_gem.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/json_gem/encoding.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/json_gem/parsing.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/lib/yajl/version.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/encoding/encoding_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/global/global_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/fixtures/http.bzip2.dump
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/fixtures/http.chunked.dump
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/fixtures/http.deflate.dump
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/fixtures/http.error.dump
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/fixtures/http.gzip.dump
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/fixtures/http.html.dump
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/fixtures/http.raw.dump
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/http_delete_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/http_error_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/http_get_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/http_post_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/http_put_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/http/http_stream_options_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/json_gem_compatibility/compatibility_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/active_support_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/chunked_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail.15.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail.16.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail.17.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail.26.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail11.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail12.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail13.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail14.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail19.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail20.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail21.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail22.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail23.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail24.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail25.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail27.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail28.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail3.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail4.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail5.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail6.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/fail9.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.array.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.codepoints_from_unicode_org.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.contacts.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.db100.xml.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.db1000.xml.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.dc_simple_with_comments.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.deep_arrays.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.difficult_json_c_test_case.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.difficult_json_c_test_case_with_comments.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.doubles.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.empty_array.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.empty_string.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.escaped_bulgarian.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.escaped_foobar.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.item.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.json-org-sample1.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.json-org-sample2.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.json-org-sample3.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.json-org-sample4-nows.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.json-org-sample4.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.json-org-sample5.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.map-spain.xml.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.ns-invoice100.xml.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.ns-soap.xml.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.numbers-fp-4k.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.numbers-fp-64k.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.numbers-int-4k.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.numbers-int-64k.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.twitter-search.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.twitter-search2.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.unicode.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass.yelp.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass1.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass2.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures/pass3.json
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/fixtures_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/parsing/one_off_spec.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/rcov.opts
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/spec/spec_helper.rb
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/tasks/compile.rake
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/tasks/rspec.rake
/Users/jpc/~/.gems/gems/yajl-ruby-1.1.0/yajl-ruby.gemspec
Building native extensions.  This could take a while...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile
make "DESTDIR="
compiling yajl.c
compiling yajl_alloc.c
compiling yajl_buf.c
compiling yajl_encode.c
compiling yajl_ext.c
compiling yajl_gen.c
yajl_gen.c:295:5: warning: implicit conversion from enumeration type
      'yajl_gen_state' to different enumeration type 'yajl_gen_status'
      [-Wenum-conversion]
    DECREMENT_DEPTH;
    ^~~~~~~~~~~~~~~
yajl_gen.c:181:48: note: expanded from macro 'DECREMENT_DEPTH'
    if (--(g->depth) >= YAJL_MAX_DEPTH) return yajl_gen_error;
                                        ~~~~~~ ^~~~~~~~~~~~~~
yajl_gen.c:321:5: warning: implicit conversion from enumeration type
      'yajl_gen_state' to different enumeration type 'yajl_gen_status'
      [-Wenum-conversion]
    DECREMENT_DEPTH;
    ^~~~~~~~~~~~~~~
yajl_gen.c:181:48: note: expanded from macro 'DECREMENT_DEPTH'
    if (--(g->depth) >= YAJL_MAX_DEPTH) return yajl_gen_error;
                                        ~~~~~~ ^~~~~~~~~~~~~~
2 warnings generated.
compiling yajl_lex.c
compiling yajl_parser.c
compiling yajl_version.c
linking shared-object yajl/yajl.bundle
ld: warning: directory not found for option '-L/usr/local/lib'
make "DESTDIR=" install
/usr/bin/install -c -m 0755 yajl.bundle ./.gem.20131025-1406-1abkfky/yajl
installing default yajl libraries
ERROR:  Error installing yajl-ruby:
    ERROR: Failed to build gem native extension.

    

Gem files will remain installed in ~/.gems/gems/yajl-ruby-1.1.0 for inspection.
Results logged to ~/.gems/gems/yajl-ruby-1.1.0/ext/yajl/gem_make.out
firstmillion:~ jpc$ 
</pre>

**Comment by zsszatmari** [comment]
Build does fail ruby 2.4 on macOS. As spykster suggested, it works on 2.1 via rvm.

**Comment by hkirsman** [comment]
Failing on me too ruby 2.4.1p111

**Comment by hkirsman** [comment]
Ah, my theme had locked yajl-ruby to 1.2.0. Changed it to 1.3.0 and works now.

**Comment by muhammednagy** [comment]
Failing on me too ruby 2.5.5p157 OSX
