### ISSUE TITLE
Fire on_parse_complete by object?

### ISSUE THREAD

**Issue by shaqq** [brianmario/yajl-ruby#159]
Hi @brianmario, thanks for writing this. I'm slightly confused on how to use Yajl to stream a large JSON file I have (1.7 Gb).

I have a JSON file that's, more a less, a huge array of JSON objects, like so:

```json
[
  {
    "foo": "bar",
    "baz": [
      {
        "nested_obj": "name",
        "nested_obj_foo": "barbar"
      }
    ]
  },
  { ... }
]
```

I could structure the JSON however way I want, but I basically need something to fire callbacks each time a JSON object is parsed. Given my example above, I was hoping that `on_parse_complete` would fire with arg like:

```ruby
  {
    foo: "bar",
    baz: [
      {
        nested_obj: "name",
        nested_obj_foo: "barbar"
      }
    ]
  }
```

Is that possible with Yajl?

**Comment by brianmario** [comment]
If you unwrap the array from the huge list of objects it should fire for every object found. For example:

```json
{"foo": "bar"}
{"foo2": "bar2"}
```

Would make `on_parse_complete` be called twice during parse. First being passed `{"foo" => "bar"}` then `{"foo2" => "bar2"}`

**Comment by shaqq** [comment]
@brianmario so my huge JSON file should look more like:

```json
{
  "some_id": {
    "foo": "bar",
    "baz": [
      {
        "nested_obj": "name",
        "nested_obj_foo": "barbar"
      }
    ]
  },
  "another_id": { ... }
}
```

Would the nested array throw off the `on_parse_complete`?

**Comment by brianmario** [comment]
The nested array should be fine. And yeah just append the json objects back to back, or even newline separated.

**Comment by shaqq** [comment]
Awesome, thanks for the quick replies!

**Comment by nagabhushanreddy** [comment]
So yajl doe not support array of objects? Whats best way to handle huge array like @shaqq case? 
```
[
  {
    "foo": "bar",
    "baz": [
      {
        "nested_obj": "name",
        "nested_obj_foo": "barbar"
      }
    ]
  },
  { ... }
]
```
